---
    - name: Add WANdisco repo
      yum_repository:
        name: WANdisco-git
        description: WANdisco Git
        file: WANdisco-git
        baseurl: http://opensource.wandisco.com/rhel/\$releasever/git/\$basearch
        gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-WANdisco

    - name: Add WANdisco repo key (for git)
      rpm_key:
        state: present
        key: http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco

    - name: Install epel-release repo
      yum:
        state: present
        name:
          - epel-release

    - name: Install tools (git, java, zip, python)
      yum:
        state: present
        name:
          - git
          - java-1.8.0-openjdk
          - python3
          - python3-pip
          - tree
          - unzip
          - zip
          - wget
          - ack
          - the_silver_searcher

